download: https://github.com/discourse/discourse.git#beta
packages:
    apt:
        - postgresql-contrib
        - libpq-dev
        - libxml2
        - imagemagick
    # TODO: empty list?
    bundler: []
databases:
    - postgresql
    - redis
data_dirs:
    - log
    - public/uploads
    - public/assets
    - public/backups
    - tmp
files:
    config/discourse.conf: |
        db_host = localhost
        db_name = {app.databases[postgresql].name}
        db_username = {app.databases[postgresql].user}
        db_password = {app.databases[postgresql].secret}
        hostname = "{app.id}"
        redis_db = {app.databases[redis].name}
        serve_static_assets = true
        serve_static_files = true
        developer_emails = {wam.config[email]}
# TODO: can one group this?
jobs:
    -
        cmd: bundle exec rails server -e production -b localhost -p {port}
        cwd: "{path}"
    -
        cmd: bundle exec sidekiq -e production
        cwd: "{path}"
hook: |
    psql -d {app.databases[postgresql].name} -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
    psql -d {app.databases[postgresql].name} -c "CREATE EXTENSION IF NOT EXISTS hstore;"
    sudo -u www-data RAILS_ENV=production bundle exec rake db:migrate
    sudo -u www-data RAILS_ENV=production bundle exec rake assets:precompile
extension_path: plugins
