download: https://github.com/discourse/discourse.git#beta
stack: ruby
packages:
    apt:
        - postgresql-contrib
        - libpq-dev
        - libxml2
        - imagemagick
    # TODO: empty list?
    bundler: []
databases:
    - postgresql
    - redis
data_dirs:
    - log
    - public/assets
    - public/backups
    - public/images
    - public/plugins
    - public/uploads
    - tmp
files:
    config/discourse.conf: |
        db_host = localhost
        db_name = {app.databases[postgresql].name}
        db_username = {app.databases[postgresql].user}
        db_password = {app.databases[postgresql].secret}
        hostname = "{app.id}"
        redis_db = {app.databases[redis].name}
        serve_static_assets = true
        serve_static_files = true
        developer_emails = {wam.config[email]}
jobs:
    - bundle exec rails server -e production -b localhost -p {app.port}
    - bundle exec sidekiq -q critical -q default -q low -e production
hook: |
    psql -d {app.databases[postgresql].name} -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
    psql -d {app.databases[postgresql].name} -c "CREATE EXTENSION IF NOT EXISTS hstore;"
    sudo -E -u www-data env PATH=$PATH RAILS_ENV=production bundle exec rake db:migrate
    sudo -E -u www-data env PATH=$PATH RAILS_ENV=production bundle exec rake assets:precompile
    # Use the default Puma config
    rm -f config/puma.rb
extension_path: plugins
