download: https://github.com/noyainrain/listling.git
stack:
    - python3
    - nodejs
packages:
    pip: []
databases:
    - redis
jobs:
    - python3 -m listling --port={app.port} --url={app.url} --redis-url={app.databases[redis].name}
hook: npm -C client update --only=prod --no-optional --no-save
