download: https://github.com/NoyaInRain/meetling.git
stack: python3
packages:
    pip: []
    bower: []
databases:
    - redis
jobs:
    - python3 -m meetling --redis-url={app.databases[redis].name} --port {app.port}
