download: https://github.com/NoyaInRain/meetling.git
stack:
    - python3
    - nodejs
databases:
    - redis
jobs:
    - python3 -m meetling --url={app.url} --redis-url={app.databases[redis].name} --port {app.port}
hook: make deps
