download: https://github.com/NoyaInRain/meetling.git
stack: python3
packages:
    apt:
        - npm
        - nodejs-legacy
databases:
    - redis
jobs:
    - python3 -m meetling --redis-url={app.databases[redis].name} --port {app.port}
hook: make deps
